// Gradle はタスクを順番に実行する仕組みを持っているだけ
// Javaのコンパイル方法などは知らない
// そのため、「Javaをコンパイルする」「サーバーを起動する」などはプラグインが持ち込んでいる

// settings.gradleでは「どのJDKを使うか」などビルド全体の話をしている
plugins {
    // toolchains: Gradleがコンパイルに使うJDKを指定する仕組みがtoolchain
    // foojay: Friends Of OpenJDK: JDKのカタログ提供屋
    // resolver: GradleがどこからJDKを入手するかを教える
    // convention: toolchainManagementの設定をかわりに書いてくれる
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

// なぜbackend/appと2階層なのか
// 将来モジュールを増やすときに下記のように簡単に増やせるため
// include('app', 'core')
rootProject.name = 'backend'
include('app')
