# Webサーバーの設定

# server: SpringのWebサーバー
# port: 通信を受け付ける番号
# ${...}: 環境変数を読む
# PORT: Renderが渡す環境変数名
# [:] :なければ右側を使う
# 8080: ローカル用の初期値
# 例えばRenderがPORT = 10000を渡すと下記と同じになる
# server.port=10000

server.port=${PORT:8080}

# app.cors.allowed-origin: 自分で命名した変数名
# FRONTEND_URL: Renderで設定する公開URL
# ここでURLを保存して、@CrossOriginがこの設定を読む
app.cors.allowed-origin=${FRONTEND_URL:http://localhost:5173}
